spring:
  application:
    name: booking-service
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:9020
        instance:
          service-base-url: http://localhost:9031
          name: Movie API Service
server:
  servlet:
    context-path: /movie/api/v1
  port: 9031
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
