server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/store/api/v1/products/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/store/api/v1/customers/**
        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/store/api/v1/shoppings/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/movie/api/v1/users/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movie/api/v1/movies/**
        - id: showtime-service
          uri: lb://showtime-service
          predicates:
            - Path=/movie/api/v1/showtimes/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/movie/api/v1/bookings/**
