spring:
  application:
    name: user-service
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:9020
        instance:
          service-base-url: http://localhost:9080
          name: User API Service
server:
  servlet:
    context-path: /movie/api/v1
  port: 9080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
